app-properties:
  jwt:
    ttl: 60
    secret: ntyS123##j5e%4nY@V4%bL7>Gk444!favJGidhaT^&2g

spring:
  datasource:
    url: jdbc:postgresql://fileshares-account-db:5432/fileshares_account
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update